# Site settings
title: Really Good Moving
header-img: img/tent.jpeg
email: davclark@gmail.com
description: "Information about the Berkeley Saturday pre-Jam Contact Improv class (1:30-3:30 at Studio8) and other movement hijinx!"
# baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://reallygoodmoving.com"
twitter_username: davclark
# github_username: davclark
facebook_username: saturdayBerkeleyJam

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: /archive/page:num
permalink: /:year/:month/:day/:title.html
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
