# Site settings
title: Really Good Moving
header-img: img/tent.jpeg
email: davclark@gmail.com
description: "Information about Feldenkrais and other movement hijinx in Baltimore!"
url: "http://reallygoodmoving.com"
twitter_username: RGMoving
# github_username: davclark
facebook_username: ReallyGoodMoving

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
permalink: /:year/:month/:day/:title.html
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",
          Makefile, Gemfile, Gemfile.lock]
gems: [jekyll-paginate-v2]
pagination:
  enabled: true
  per_page: 5
  permalink: /archive/page:num
  sort_reverse: true

# Show posts with dates in the future
future: true

# We keep heavy files here
keep_files: ["media"]
